/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AlumnoData;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import proyectotranversalulp.Entidades.Alumno;

/**
 *
 * @author kalema
 */
public class GestionAlumnos extends javax.swing.JInternalFrame {

    public DefaultTableModel modelo = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int filas, int columnas) {
            return false;
        }
    };

    AlumnoData abmAlumno = new AlumnoData();
    Alumno temp=new Alumno();

    /**
     * Creates new form GestionAlumnos
     */
    public GestionAlumnos() {
        initComponents();
        armoTabla();
        camposActivosInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaResultado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtBusqudaDNI = new javax.swing.JTextField();
        jbtNuevoAlumno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtFechaNac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboEstado = new javax.swing.JComboBox<>();
        jbtAgregar = new javax.swing.JButton();
        jbtModificar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtBaja = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jEtiquetaID = new javax.swing.JLabel();

        jTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablaResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaResultado);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel1.setText("Ingrese  el Nº DNI");
        jLabel1.setFocusable(false);

        jtBusqudaDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBusqudaDNIKeyReleased(evt);
            }
        });

        jbtNuevoAlumno.setText("Nuevo Alumno");

        jLabel2.setText("Nombre");
        jLabel2.setFocusable(false);

        jLabel3.setText("Apellido");
        jLabel3.setFocusable(false);

        jLabel4.setText("Fecha Nac.");

        jLabel5.setText("Estado");
        jLabel5.setFocusable(false);

        jbtAgregar.setText("Agregar");

        jbtModificar.setText("Modificar");

        jbtCancelar.setText("Cancelar");

        jbtBaja.setText("Baja");

        jLabel6.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtBusqudaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtNuevoAlumno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jEtiquetaID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtBaja)
                                .addGap(18, 18, 18)
                                .addComponent(jbtModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbtCancelar))
                            .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtBusqudaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNuevoAlumno))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jEtiquetaID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtModificar)
                    .addComponent(jbtAgregar)
                    .addComponent(jbtCancelar)
                    .addComponent(jbtBaja))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBusqudaDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBusqudaDNIKeyReleased
        // Procedimiento de búsqueda por dni para el alta o la edición de un alumno
        borrarFilas();
        List<Alumno> miLista = new ArrayList();
        miLista=abmAlumno.listarAlumnos();
        if (jtBusqudaDNI.getText().isEmpty()) {
            borrarFilas();
            jbtNuevoAlumno.setEnabled(false);
        } else {
            for (Alumno alu : miLista) {
                String cadenaDNI = String.valueOf(alu.getDni());
                if (cadenaDNI.startsWith(jtBusqudaDNI.getText())) {
                    modelo.addRow(new Object[]{alu.getIdAlumno(), alu.getNombre(), alu.getApellido(),
                        alu.getDni(), alu.getFechaNacimiento(), alu.isEstado()});
                }
                if(modelo.getRowCount() == 0 && jtBusqudaDNI.getText().length()>=8){
                    jbtNuevoAlumno.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_jtBusqudaDNIKeyReleased

    private void jTablaResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaResultadoMouseClicked
        // Procedimiento que carga los valores seleccionados en la tabla a los campos para edición
        int valor=jTablaResultado.getSelectedRow();
        String aluID=String.valueOf(modelo.getValueAt(valor,0));
        String aluNom=String.valueOf(modelo.getValueAt(valor, 1));
        String aluApe=String.valueOf(modelo.getValueAt(valor, 2));
        String aluFecha=String.valueOf(modelo.getValueAt(valor, 4));
        String aluEstado=String.valueOf(modelo.getValueAt(valor, 5));
        temp.setIdAlumno((int) modelo.getValueAt(valor, 0));
        temp.setNombre((String) modelo.getValueAt(valor, 1));
        temp.setApellido((String) modelo.getValueAt(valor, 2));
        temp.setDni((int) modelo.getValueAt(valor, 3));
        temp.setFechaNacimiento((LocalDate.parse((CharSequence) modelo.getValueAt(valor, 4))));
        temp.setEstado((boolean)modelo.getValueAt(valor, 5));
        
        jtNombre.setText(aluID);
        jtNombre.setText(aluNom);
        jtApellido.setText(aluApe);
        jtFechaNac.setText(aluFecha);
        //jComboEstado.getModel().setSelectedItem();
        
    }//GEN-LAST:event_jTablaResultadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JLabel jEtiquetaID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaResultado;
    private javax.swing.JButton jbtAgregar;
    private javax.swing.JButton jbtBaja;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JButton jbtNuevoAlumno;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtBusqudaDNI;
    private javax.swing.JTextField jtFechaNac;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables

    private void armoTabla() {
        modelo.addColumn("Identificador");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Fecha Nac.");
        modelo.addColumn("Estado");
        jTablaResultado.setModel(modelo);
    }

    private void camposActivosInicial() {
        jbtNuevoAlumno.setEnabled(false);
        jtNombre.setEnabled(false);
        jtApellido.setEnabled(false);
        jtFechaNac.setEnabled(false);
        jComboEstado.setEnabled(false);
        jbtAgregar.setEnabled(false);
        jbtBaja.setEnabled(false);
        jbtModificar.setEnabled(false);
        jbtCancelar.setEnabled(false);
    }

    private void borrarFilas() {
        int filas = modelo.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
    private void cargoComb(){
        jComboEstado.addItem("Acitvo");
        jComboEstado.addItem("Desacivado");
    }
}
